### ISSUE TITLE
Error by running dailyblink 

### ISSUE THREAD

**Issue by fugohan** [ptrstn/dailyblink#19]
```
Downloading the free daily Blinks...

Traceback (most recent call last):
  File "/home/user/.local/bin/dailyblink", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/dailyblink/__main__.py", line 66, in main
    download_blinks(scraper, languages, base_path)
  File "/home/user/.local/lib/python3.8/site-packages/dailyblink/utils.py", line 18, in download_blinks
    blink_info = get_daily_blink_info(scraper=scraper, language=language_code)
  File "/home/user/.local/lib/python3.8/site-packages/dailyblink/core.py", line 39, in get_daily_blink_info
    return _create_blink_info(response.text)
  File "/home/user/.local/lib/python3.8/site-packages/dailyblink/core.py", line 22, in _create_blink_info
    cover_url = soup.find_all("img", {"class": "book-cover__image"})[0]["src"]
IndexError: list index out of range
```

**Comment by fugohan** [comment]
fixed with new release
