### ISSUE TITLE
I'm unable to download a German blink

### ISSUE THREAD

**Issue by Puppe1eer** [ptrstn/dailyblink#21]
What am i doing wrong? The program worked just fine until it stopped downloading German books and audio files since yesterday. That's the output result, can someone help me please? 

cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

During handling of the above exception, another exception occurred:

UnicodeEncodeError: 'charmap' codec can't encode character '\u2082' in position 14908: character maps to <undefined>
Downloading the free daily Blinks...
Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.
Retrying...
Attempt 1/10... FAILED
Attempt 2/10... FAILED
Attempt 3/10... FAILED
Attempt 4/10... FAILED
Attempt 5/10...
german (de):
2030 - Mauro F. Guillen

Saving book text...

**Comment by ptrstn** [comment]
What version of dailyblink are you using? Did you update/upgrade the package? What command did you use? Whats the completely error message output?

See:
- https://github.com/ptrstn/dailyblink/issues/20#issuecomment-1001200336

**Comment by Puppe1eer** [comment]
Funnily enough, the code was working till yesterday. I'm still stuck on using the 1.0.0 version, because the `pip install --upgrade --user git+https://github.com/ptrstn/dailyblink` command is just downloading the newer versions of the mutagen and beatifulsoup4, but it isn't replacing them with the older files.
I'm quite a noob in this kind of stuff...

**Comment by Puppe1eer** [comment]
I also have tried searching for fragments of older versions and reinstalling the program like it was mentioned in the other issue comment, but it isn't solving my problem.
That's the output message: 
```
mposq@DESKTOP-EPIOKKE MINGW67 ~
$ python -m dailyblink
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

During handling of the above exception, another exception occurred:

UnicodeEncodeError: 'charmap' codec can't encode character '\u2060' in position 345: character maps to <undefined>
Downloading the free daily Blinks...
Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.
Retrying...
Attempt 1/10...
english (en):
What is Life? - Erwin Schr▒dinger

Saving book text...
```

**Comment by ptrstn** [comment]
What operating system do you use? Python version? How did you initially install the programm? 

If you use Windows, try this: 
https://github.com/ptrstn/dailyblink/issues/20#issuecomment-1001703520

**Comment by kotzer3** [comment]
Same issue here on windows. Still same version 1.0.0 (as #20)
Some encoding issue related to win?

**Comment by ptrstn** [comment]
I really can't help you if you don't provide me with enough information, or at least the information I asked for.
I assume thats a related Windows issue, since all daily GitHub actions ran fine. 

Judging on the error message provided by @Puppe1eer I assume that there is a special character in the book text that can't be properly decoded by some operating systems.

[```\u2060```](https://www.fileformat.info/info/unicode/char/2082/index.htm) is the Unicode character  'SUBSCRIPT TWO':  ```₂```
I assume coming from this text in Blink 5 of 2030 by Mauro F. Guillen:

> Tatsächlich sind Städte für 75 Prozent des globalen Energieverbrauchs und 80 Prozent der globalen CO₂-Emissionen verantwortlich.

['\u2060'](https://www.fileformat.info/info/unicode/char/2060/index.htm) is the is the Unicode character  'WORD JOINER'.
Since I didn't save that blink, I dont know where exactly in the text it appeared.

I'll run some tests.

**Comment by ptrstn** [comment]
Should be fixed in version ```1.0.1```

**Comment by Puppe1eer** [comment]
It's working again, thank you very much, you have done a great job!

**Comment by kotzer3** [comment]
Hi Peter, am very sorry, (and don't know) if still related to same problem (#21) but after upgrading to newest version (1.0.1) Index out of range :/

I already updated the dailyblink by the commands you provided in #20 via:
```
pip uninstall dailyblink
pip install --user git+https://github.com/ptrstn/dailyblink
```

I saw, that [todays github actionjob](https://github.com/ptrstn/dailyblink/runs/4946070201?check_suite_focus=true) still without any errors: 

here full stack (and hopefully the version infos you need?)
```
Microsoft Windows [Version 10.0.19042.985]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\tbr>python --version
Python 3.9.9

C:\Users\tbr>python -m dailyblink -version
usage: __main__.py [-h] [--version] [-p PATH] [-l {en,de} [{en,de} ...]]
__main__.py: error: unrecognized arguments: -version

C:\Users\tbr>python -m dailyblink --version
__main__.py 1.0.1

C:\Users\tbr>python -m dailyblink
Downloading the free daily Blinks...
Traceback (most recent call last):
  File "C:\Users\tbr\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tbr\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\__main__.py", line 54, in <module>
    main()
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\__main__.py", line 50, in main
    blinkist_scraper.download_daily_blinks(args.language, base_path)
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\core.py", line 32, in download_daily_blinks
    self._attempt_daily_blinks_download(languages, base_path)
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\core.py", line 51, in _attempt_daily_blinks_download
    self._download_daily_blinks(language_code, base_path)
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\core.py", line 58, in _download_daily_blinks
    blink_info = self._get_daily_blink_info(language=language_code)
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\core.py", line 116, in _get_daily_blink_info
    return _create_blink_info(response.text)
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\core.py", line 161, in _create_blink_info
    daily_book_href = soup.find_all("a", {"class": "daily-book__cta"})[0]["href"]
IndexError: list index out of range

C:\Users\tbr>pip uninstall dailyblink
Found existing installation: dailyblink 1.0.1
Uninstalling dailyblink-1.0.1:
  Would remove:
    c:\users\tbr\appdata\roaming\python\python39\scripts\dailyblink-script.py
    c:\users\tbr\appdata\roaming\python\python39\scripts\dailyblink.exe
    c:\users\tbr\appdata\roaming\python\python39\site-packages\dailyblink-1.0.1-py3.9.egg-info
    c:\users\tbr\appdata\roaming\python\python39\site-packages\dailyblink\*
Proceed (Y/n)? Y
  Successfully uninstalled dailyblink-1.0.1

C:\Users\tbr>pip install --user git+https://github.com/ptrstn/dailyblink
Collecting git+https://github.com/ptrstn/dailyblink
  Cloning https://github.com/ptrstn/dailyblink to c:\users\tbr\appdata\local\temp\pip-req-build-ogxr61no
  Running command git clone --filter=blob:none -q https://github.com/ptrstn/dailyblink 'C:\Users\tbr\AppData\Local\Temp\pip-req-build-ogxr61no'
  Resolved https://github.com/ptrstn/dailyblink to commit f1792f9c1d3de6e12a72e265957fdb03e702fc0b
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in c:\users\tbr\appdata\roaming\python\python39\site-packages (from dailyblink==1.0.1) (2.26.0)
Requirement already satisfied: beautifulsoup4 in c:\users\tbr\appdata\roaming\python\python39\site-packages (from dailyblink==1.0.1) (4.10.0)
Requirement already satisfied: mutagen in c:\users\tbr\appdata\roaming\python\python39\site-packages (from dailyblink==1.0.1) (1.45.1)
Requirement already satisfied: cloudscraper in c:\users\tbr\appdata\roaming\python\python39\site-packages (from dailyblink==1.0.1) (1.2.58)
Requirement already satisfied: soupsieve>1.2 in c:\users\tbr\appdata\roaming\python\python39\site-packages (from beautifulsoup4->dailyblink==1.0.1) (2.3.1)
Requirement already satisfied: pyparsing>=2.4.7 in c:\users\tbr\appdata\roaming\python\python39\site-packages (from cloudscraper->dailyblink==1.0.1) (3.0.6)
Requirement already satisfied: requests-toolbelt>=0.9.1 in c:\users\tbr\appdata\roaming\python\python39\site-packages (from cloudscraper->dailyblink==1.0.1) (0.9.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tbr\appdata\roaming\python\python39\site-packages (from requests->dailyblink==1.0.1) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tbr\appdata\roaming\python\python39\site-packages (from requests->dailyblink==1.0.1) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\tbr\appdata\roaming\python\python39\site-packages (from requests->dailyblink==1.0.1) (2.0.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\tbr\appdata\roaming\python\python39\site-packages (from requests->dailyblink==1.0.1) (1.26.7)
Using legacy 'setup.py install' for dailyblink, since package 'wheel' is not installed.
Installing collected packages: dailyblink
    Running setup.py install for dailyblink ... done
Successfully installed dailyblink-1.0.1

C:\Users\tbr>python -m dailyblink --version
__main__.py 1.0.1

C:\Users\tbr>python -m dailyblink
Downloading the free daily Blinks...
Traceback (most recent call last):
  File "C:\Users\tbr\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tbr\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\__main__.py", line 54, in <module>
    main()
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\__main__.py", line 50, in main
    blinkist_scraper.download_daily_blinks(args.language, base_path)
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\core.py", line 32, in download_daily_blinks
    self._attempt_daily_blinks_download(languages, base_path)
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\core.py", line 51, in _attempt_daily_blinks_download
    self._download_daily_blinks(language_code, base_path)
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\core.py", line 58, in _download_daily_blinks
    blink_info = self._get_daily_blink_info(language=language_code)
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\core.py", line 116, in _get_daily_blink_info
    return _create_blink_info(response.text)
  File "C:\Users\tbr\AppData\Roaming\Python\Python39\site-packages\dailyblink\core.py", line 161, in _create_blink_info
    daily_book_href = soup.find_all("a", {"class": "daily-book__cta"})[0]["href"]
IndexError: list index out of range

C:\Users\tbr>
```
