### ISSUE TITLE
Broken as of 15/03/2022

### ISSUE THREAD

**Issue by MANICX100** [ptrstn/dailyblink#31]
**Version of dailyblink**: 1.1.1
**Python version**:  3.10.2
**Operating system**:  Win 11
```bash
python -m dailyblink --language en
```

```python
Traceback (most recent call last):
  File "C:\Users\dmani\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dmani\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\dmani\AppData\Roaming\Python\Python310\site-packages\dailyblink\__main__.py", line 6, in <module>
    from dailyblink.core import BlinkistScraper
  File "C:\Users\dmani\AppData\Roaming\Python\Python310\site-packages\dailyblink\core.py", line 9, in <module>
    from cloudscraper import CloudflareChallengeError
ImportError: cannot import name 'CloudflareChallengeError' from 'cloudscraper' (C:\Users\dmani\AppData\Local\Programs\Python\Python310\lib\site-packages\cloudscraper\__init__.py)```

**Comment by ptrstn** [comment]
Seems like [cloudscraper](https://pypi.org/project/cloudscraper/) is broken. They released a new version ([1.2.60](https://pypi.org/project/cloudscraper/1.2.60/)) 6 hours ago:
https://pypi.org/project/cloudscraper/#history

Since they [don't accept any issues](https://github.com/VeNoMouS/cloudscraper), there's nothing I can do for now, other than downgrading cloudscraper. 

```
pip install cloudscraper==1.2.58
```

Should be fixed as of dailyblink version 1.2.1

```
pip install --upgrade --user git+https://github.com/ptrstn/dailyblink
```
