### ISSUE TITLE
Failed to set m4a tags today

### ISSUE THREAD

**Issue by NicoWeio** [ptrstn/dailyblink#9]
For so far unknown reasons, this program could not set tags on today's (2021-05-15) German free blink, **Meisterkurs Rhetorik - Benedikt Held**.

```
Traceback (most recent call last):
  File "/home/nicolai/Daten/Programmieren/1 GitHub-Forks/dailyblink/dailyblink/blinks.py", line 207, in <module>
    main()
  File "/home/nicolai/Daten/Programmieren/1 GitHub-Forks/dailyblink/dailyblink/blinks.py", line 189, in main
    set_m4a_meta_data(
  File "/home/nicolai/Daten/Programmieren/1 GitHub-Forks/dailyblink/dailyblink/blinks.py", line 130, in set_m4a_meta_data
    tags["\xa9ART"] = artist
TypeError: 'NoneType' object does not support item assignment
```

I fixed it by adding 

```
if not tags:
    print("WARN: Cannot apply tags to m4a!")
    return
```
to `set_m4a_meta_data`.

I will keep an eye on this…

**Comment by ManuelSchneid3r** [comment]
@NicoWeio hat der Download für dich noch funktioniert am Ende? Könntest du mir den Blink schicken falls ja?

**Comment by ManuelSchneid3r** [comment]
Bei "Kreativität - Melanie Raabe", und "Der Mensch und seine Symbole - Carl Gustav Jung" scheint das selbe passiert zu sein.

**Comment by NicoWeio** [comment]
> Bei "Kreativität - Melanie Raabe", und "Der Mensch und seine Symbole - Carl Gustav Jung" scheint das selbe passiert zu sein.

Bei mir ebenso. War mir noch gar nicht aufgefallen. For reference: 07.05.21 und 14.05.21 sind die anderen betroffenen Daten. 

Ich kann dir die mit meinem Fix heruntergeladenen Blinks gerne schicken, aber sehe bei dir keine E-Mail-Adresse oder dergleichen.

---
PS: Du bist „führender Entwickler“ von _Albert_? Ist ja cool, Albert habe ich eine Zeit lang gerne benutzt. :)

**Comment by ManuelSchneid3r** [comment]
> PS: Du bist „führender Entwickler“ von _Albert_? Ist ja cool, Albert habe ich eine Zeit lang gerne benutzt. :)

ja, freut mich immer zu hören.

das problem ist hiermit https://github.com/ptrstn/dailyblink/pull/11 gefixt
